apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gpm108sbo-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gpm108sbo-nodejs 
  name: gpm108sbo-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: gpm108sbo-nodejs 
